include ../.env.prod

fetch_articles:
	curl -i --location --request POST '$(BACKEND_URL)/global/articles' \
		--header 'x-api-key: $(BACKEND_API_KEY)' \
		--header 'Content-Type: application/json';

reset:
	supabase link --project-ref $(PROJECT_ID) \
		&& mv migrations /tmp/_migrations_backup \
		&& mv seeds /tmp/_seeds_backup \
		&& supabase db reset --linked \
		; mv /tmp/_migrations_backup migrations \
		; mv /tmp/_seeds_backup seeds

seed:
	supabase link --project-ref $(PROJECT_ID) \
		&& supabase db push --include-seed

deploy:
	supabase link --project-ref $(PROJECT_ID) \
		&& supabase db push --include-all \
		&& supabase secrets set \
			BACKEND_URL=$(BACKEND_URL) \
			BACKEND_API_KEY=$(BACKEND_API_KEY) \
		&& echo " \
			DELETE FROM vault.secrets WHERE name IN ('backend_url', 'backend_api_key'); \
			SELECT vault.create_secret('$(BACKEND_URL)', 'backend_url'); \
			SELECT vault.create_secret('$(BACKEND_API_KEY)', 'backend_api_key'); \
		" | psql "postgresql://postgres:$(PROJECT_PASSWORD)@db.$(PROJECT_ID).supabase.co:5432/postgres"

update:
	supabase link --project-ref $(PROJECT_ID) \
		&& supabase db push --include-all

init: reset deploy seed fetch_articles
