include ../.env.prod

reset:
	supabase link --project-ref $(PROJECT_ID) \
		&& (supabase functions delete fetch_articles || true) \
		&& (supabase functions delete embed || true) \
		&& (supabase functions delete parse_feed || true) \
		&& mv migrations /tmp/_migrations_backup \
		&& mv seeds /tmp/_seeds_backup \
		&& supabase db reset --linked \
		; mv /tmp/_migrations_backup migrations \
		; mv /tmp/_seeds_backup seeds

deploy:
	supabase link --project-ref $(PROJECT_ID) \
		&& supabase db push --include-seed --include-all \
		&& supabase secrets set \
			OPENAI_API_KEY=$(OPENAI_API_KEY) \
			NEXT_PUBLIC_URL=$(NEXT_PUBLIC_URL) \
			REVALIDATE_SECRET=$(REVALIDATE_SECRET) \
		&& echo " \
			DELETE FROM vault.secrets WHERE name IN ('project_url', 'publishable_key'); \
			SELECT vault.create_secret('$(PROJECT_URL)', 'project_url'); \
			SELECT vault.create_secret('$(PUBLISHABLE_KEY)', 'publishable_key'); \
		" | psql "$(DATABASE_URL)" \
		&& supabase functions deploy fetch_articles \
		&& supabase functions deploy embed \
		&& supabase functions deploy parse_feed
